### ISSUE TITLE
can I use multiple xml file?

### ISSUE THREAD

**Issue by DanielChen93** [rticommunity/rticonnextdds-connector-js#131]
can `rticonnextdds-connector-js` use multiple xml files? 
the use case will be a main xml file use some types from another xml file.
Thanks.

**Comment by samuelraeburn** [comment]
Hi @DanielChen93, yes that is supported.

See where we do it in [this unit test](https://github.com/rticommunity/rticonnextdds-connector-js/blob/master/test/nodejs/test_rticonnextdds_connector.js#L84-L94).

Connector relies on the XML Application Creation feature from Connext DDS Pro (see [here)](https://community.rti.com/static/documentation/connector/1.2.1/api/javascript/configuration.html). The documentation for XML app creation is [here](https://community.rti.com/static/documentation/connext-dds/6.1.1/doc/manuals/connext_dds_professional/xml_application_creation/index.htm).
