### ISSUE TITLE
sleep dependency

### ISSUE THREAD

**Issue by daniel-white-1990** [rticommunity/rticonnextdds-connector-js#99]
Hi guys,

I notice that sleep is now a dependency of the connector (but not mentioned in the README and seemingly only used in the examples).

I am having an issue with installing the connector as the build of sleep is failing on my machine due to a timeout connecting to a specific IP. Which I suspect is in some way related to the proxy/infrastructure I am working behind.

Would it be possible to review this dependency to either provide an insight into why this is failing (I cannot see any related issues in the sleep repo), or ideally make it optional as it is only used in the example code.

Thanks,
Daniel

**Comment by samuelraeburn** [comment]
Hi,
I have raised an internal improvement, CON-256, to remove the dependency on sleep (instead we can use Atomics.wait()).

Can you provide more details on your issue, and I'll see if I can work out what is going on

**Comment by daniel-white-1990** [comment]
Hi,

Thanks for raising an internal ticket - if I may suggest perhaps it is better to distribute the examples separately from the main connector if possible?

The issue is resolved on my end - it was in fact a proxy issue with node-gyp trying to download the nodejs headers. Which in fact meant I only noted sleep as it was the first dependency that npm attempted to compile.

Going to close this issue as a result but thanks for your help :)
